### PR TITLE
First Microverse Project ( Pull Request Practice)

### PR DESCRIPTION
**Pull request by musangamfure**
This is my simple HTML_CSS project for solidifying my knowledge on:

1. Github workflows
2. Linters
3. Pull request message
4. Professional README writing

### CODE REVIEW

**Review by OyePriscilla — CHANGES_REQUESTED** [review]
Hi @musangamfure 👏 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

so-close

## Highlights
Add .html and .css files 👍 
Observe GitHub Flow ✔️ 


## Required Changes ♻️

- [ ] Please kindly customize [Microverse README template](https://github.com/microverseinc/readme-template), ensure to fill all the sections except for FAQ which is optional. This will make your repo looks professional and gives visitors some information about your project. 👍 

- [ ] Kindly make your PR title and branch name to be more descriptive. The PR title suppose to be a summary of all you've done in the branch so far (e.g. Hello Microverse project). The branch name too should be a summary of what you did in the branch. **Kindly checkout to the new branch and use the correct branch name and mention the old PR in the new PR.**

- [ ] Please note that all linters are expected to pass, kindly ensure that the lighthouse linter check is passing. 👍 

## Optional suggestions

- [optional] Always ensure to effect all the requirement for a milestone in a branch, I could noticed that you've already added .gitignore file to the main branch. ℹ️ 

- [optional] Kindly ensure that your commit messages are always in imperative tense and capitalized. ℹ️ 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by musangamfure** [comment]
Hello @OyePriscilla,

Thank you so much for your kind and insightful review of my first project. I have made all the corrections as per your suggestion and guidance.  all the changes are visible on my second branch which hello-microverse-project. Kindly let me know if I passed at this time. I did not open a new re-review as you suggested. 

Thanks.

**Review by osamaashraf6 — APPROVED** [review]

**Review by osamaashraf6 — COMMENTED** [review]
.

**Review by osamaashraf6 — CHANGES_REQUESTED** [review]
.

**Review by osamaashraf6 — COMMENTED** [review]
.

**Pull request closed without merging**
